package com.dicoding.picodiploma.wisatalombok;

import java.util.ArrayList;

public class WisataData {
    public static String[][] data = new String[][]{
            {"Pantai Senggigi", "Lombok Barat", "Gratis", "Pantai Senggigi adalah salah satu tempat wisata di Lombok yang paling ramai dikunjungi oleh para wisatawan, lokasinya berada di bagian barat Pulau Lombok, Pantai Senggigi mempunyai suasana yang mirip dengan Pantai Kuta di Bali, namun mempunyai ombak yang tenang sehingga sangat cocok untuk kegiatan berenang dan snorkeling. Mempunyai garis pantai yang panjang, pantai ini akan memanjakan Anda dengan keindahan pasir pantai dan air laut yang jernih, karena merupakan salah satu tempat wisata di Lombok yang paling terkenal. Pantai Senggigi mempunyai fasilitas penunjang wisata seperti restoran, hotel, bar, sarana transportasi, dan aneka fasilitas lainnya yang sangat lengkap.", "https://mytrip123.com/wp-content/uploads/2016/01/Pantai-Senggigi-Lombok-633x420.jpg"},
            {"Pantai Kuta Lombok", "Lombok Tengah", "Gratis", "Tak hanya pulau Bali yang memiki pantai kuta dengan sansetnya yang istimewa, ternyata Lombok juga memiliki pantai kuta yang tak kalah cantiknya. Pantai kuta berada di Desa Kuta, sekitar 56 KM dari kota Mataram, Lombok.\n" +
                    "Pantai Kuta Lombok mempunyai pasir yang sehalus merica, oleh karena itu banyak penduduk setempat yang menyebut pantai ini sebagai pantai merica. Pantai Kuta Lombok adalah salah satu tempat wisata di Lombok yang paling indah, bahkan juga salah satu yang terindah di Indonesia karena masih jarang dijamah oleh gangguan manusia.\n" +
                    "Wisata utama di pantai ini adalah selancar karena ombaknya yang merupakan salah satu yang terbaik di dunia. Wisata lain yang dapat dilakukan di Pantai Kuta Lombok di antaranya: memancing, menyelam, snorkeling, dan aneka kegiatan lainnya yang tak kalah menyenankan.", "https://mytrip123.com/wp-content/uploads/2016/01/Pantai-Kuta-Lombok-Yang-Menawan.jpg"},
            {"Gunung Rinjani", "Lombok Timur", "Gratis", "Gunung Rinjani adalah ikon wisata sekaligus tempat wisata di Lombok yang paling terkenal. Dengan ketinggian lebih dari 3,700 meter, gunung rinjani adalah gunung berapi tertinggi kedua di Indonesia. Bagi penganut agama Hindu, Gunung Rinjani mempunyai nilai spiritual tersendiri karena dianggap merupakan tempat tinggal dari pada dewa.\n" +
                    "Wisata favorit di gunung rinjadi ini adalah pendakian. Gunung rinjani dianggap sebagai gunung dengan pemandangan terindah di Asia, sehingga banyak orang yang mendaki gunung ini untuk dapat menikmati pemandangan yang tiada duanya. Untuk dapat mencapai puncak gunung rinjani, Anda akan membutuhkan waktu beberapa hari, oleh karena itu persiapkanlah dengan matang segala kebutuhan Anda jika ingin berkunjung di gunung rinjani ini.", "https://mytrip123.com/wp-content/uploads/2016/01/gunung-rinjani-wisata-lombok.jpg"},
            {"Pantai Sekotong", "Lombok Barat", "Gratis", "Pantai Sekotong terdapat di Kecamatan Sekotong, Lombok Barat, sekitar 60 km dari Kota Mataram. Pantai ini dikelilingi oleh perbukitan yg melingkar tidak jauh dari tepi pantai.\n" +
                    "Lautnya yg biru serta pantainya yang putih menjadikan tempat ini sebagai obyek wisata di Pulau Lombok yang wajib dikunjungi. Pantai Sekotong ini masih sangat asri, bebas polusi dan belum banyak dijamah oleh wisatawan.", "https://mytrip123.com/wp-content/uploads/2016/01/wisata-lombok-pantai-sekotong.jpg"},
            {"Pura Batu Bolong", "Lombok Barat", "Gratis", "Pura Batu Bolong terletak di daerah Senggigi, Lombok. Pura Batu Bolong berada di atas sebuah batu karang berwarna hitam yang menjorok ke arah laut. Di bagian tengah batu karang ini terdapat sebuah lubang, sehingga pura ini dinamakan Pura Batu Bolong.\n" +
                    "Seperti pura-pura pada umumnya di Bali, untuk dapat memasuki Pura Batu Bolong, Anda harus menggunakan kain berwarna kuning di pinggang. Pura Batu Bolong mempunyai latar belakang pemandangan Gunung Agung dan Selat Lombok, sehingga sangat indah sekali untuk berfoto – foto, terutama pada saat matahari tenggelam.", "https://mytrip123.com/wp-content/uploads/2016/01/pura-batu-bolong-wisata-lombok.jpg"},
            {"Taman Narmada", "Lombok Barat", "Gratis", "Taman Narmada berlokasi di Desa Lembuak, sekitar 10 km di sebelah timur kota Mataram. Taman seluas kurang lebih 2 hektar ini dibangun oleh Raja Mataram Lombok pada tahun 1727. Dulunya, taman ini digunakan sebagai tempat istirahat dan tempat upacara, namun sekarang ini, taman telah beralih fungsi menjadi tempat wisata.\n" +
                    "Hal unik dari Taman Narmada adalah desain taman yanh merupakan replika mini dari gunung rinjani, selain itu terdapat juga sumber mata air dari gunung rinjani yang dipercaya dapat membuat Anda awet muda bila Anda membasuh muka dan meminum air tersebut.", "https://mytrip123.com/wp-content/uploads/2016/01/taman-narmada-lombok.jpg"},
            {"Gili Nanggu", "Lombok Barat", "Gratis", "Gili Nanggu berada di Selat Lombok atau di pesisir barat Pulau Lombok. Secara administratif, pulau ini berada di wilayah Kecamatan Sekotong, Kabupaten Lombok Barat.\n" +
                    "Di Gili Nanggu terdapat pantai cantik dengan hamparan pasirnya yang putih serta lautnya yang biru. Suasana alamnya yang hening, membuat pulau ini menjadi pilihan yang tepat bagi para pasangan yang ingin berbulan madu. Matahari tenggelam merupakan momen yang paling indah di pulau seluas sekitar 8 hektar ini", "https://mytrip123.com/wp-content/uploads/2016/01/Gili-Nanggu-Lombok.jpg"},
            {"Air Terjun Sendang Gile", "Lombok Utara", "Gratis", "Berlokasi di Lombok Utara, Air Terjun Sendang Gile berjarak sekitar 60 km atau 3 jam perjalanan dari kota Mataram. Berada di kawasan Desa Senaru, Air Terjun Sendang Gile adalah pintu masuk awal pendakian Gunung Rinjani.\n" +
                    "Karena memiliki sumber air yang sama dengan air di Taman Narmada, air di Air Terjun Sendang Gile juga dipercaya dapat membuat Anda awet muda bila Anda gunakan untuk mandi atau membasuh muka. Untuk dapat menikmati air awet muda di Air Terjun Sendang Gile, Anda harus menaiki sekitar 200 anak tangga terlebih dahulu.", "https://mytrip123.com/wp-content/uploads/2016/01/sendang-gile-wisata-lombok.jpg"},
            {"Gili Trawangan, Gili Meno, Gili Air", "Lombok Barat", "Gratis", "Ketiga pulau itu seakan mampu mewakili potret keindahan pantai – pantai di Lombok. Semuanya menyajikan kebeningan air laut, butiran pasir putih tanpa serakan sampah, serta terumbu karang dengan ikan hias yang menggemaskan.\n" +
                    "Ketiga pulau mungil yang berada di tengah lautan itu memiliki perbedaan karakteristik yang unik. Masing – masing punya suasana alam dan ciri khas tersendiri. Bahkan, akhirnya perbedaan itu seakan memilah wisatawan sesuai dengan minat, sifat, dan kepribadiannya.\n" +
                    "Gili Trawangan merupakan pulau terbesar, teramai sekaligus terjauh dari pulau utama Lombok. Kebanyakan wisatawan yang mengunjunginya terdiri dari orang-orang yang berjiwa muda dan penuh semangat.\n" +
                    "Sementara itu, Gili Meno yang terletak di tengah-tengah antara Gili Trawangan dan Gili Air, lebih sesuai bagi wisatawan yang mengidamkan relaksasi di tengah kesunyian. Pengunjung benar – benar disuguhi nuansa alami pantai tropis yang tenang. Pepohonan bakau masih terlihat merimpun di sepanjang pesisir pantainya.\n" +
                    "Lain lagi dengan suasana yang tercipta di Gili Air. Pulau yang terdekat dari Lombok ini lebih sesuai bagi wisatawan yang berlibur bersama keluarga. Dihuni penduduk lokal paling banyak, pulau ini lebih menawarkan suasana pantai yang tidak ramai namun tidak terlalu sepi.\n" +
                    "Meskipun berada di tengah lautan, para wisatawan tak usah cemas memikirkan transportasi, akomodasi maupun urusan perut. Semua fasilitas wisata tersedia lengkap. Masing-masing pulau memiliki hotel, restoran, diskotek sampai tempat ibadah sekalipun. Semua kemudahan itu menjamin kenyamanan liburan yang menyenangkan.", "https://mytrip123.com/wp-content/uploads/2016/01/Gili-Trawangan-Lombok-631x420.jpg"},
            {"Danau Segara Anak", "Lombok Timur", "Gratis", "Danau Segara Anak merupakan salah satu tempat yang juga wajib dikunjungi, terutama bagi para pecinta wisata alam. Berlokasi di kawah Gunung Rinjani, Danau Segara Anak sampai sekarang masih diyakini sebagai bagian dari laut yang terpecah ke atas sebuah pulau. Hal ini dikarenakan warna air danau ini yang berwarna biru, persis sama seperti warna air laut.\n" +
                    "Biasanya apabila Anda mengambil paket mendaki Gunung Rinjani bersama dengan biro perjalanan, Anda juga akan dibawa menuju Danau Segara Anak dan bermalam di pinggir danau. Kegiatan utama di danau ini adalah memancing, oleh karena itu jangan lupa membawa alat pancing Anda. Untuk dapat mencapai lokasi Danau Segara Anak, Anda harus berjalan kaki selama kurang lebih 9 jam dari titik akhir jalur yang dapat dilalui kendaraan bermotor, melelahkan namun pasti tidak akan mengecewakan.", "https://mytrip123.com/wp-content/uploads/2016/01/danau-segara-anakan-lombok.jpg"},
            {"Pantai Sire", "Lombok Utara", "Gratis", "Pantai Sire yang ada di Lombok Utara berjarak kurang lebih 35 km dari kota Mataram. Pantai Sire adalah tempat wisata di Lombok yang layak dikunjungi karena keindahan yang ditawarkan. Apabilala cuaca sedang cerah, Anda dapat melihat Gunung Rinjani dari pantai ini.\n" +
                    "Dengan garis pantai hampir 4 km, Pantai Sire menawarkan aktifitas wisata yang cukup beragam seperti berenang, snorkeling, bermain kano, sampai dengan memancing. Bila Anda tidak membawa peralatan wisata untuk kegiatan tersebut, tidak perlu kuatir karena di pinggir Pantai Sire banyak terdapat penyewaan alat-alat penunjang wisata.", "https://mytrip123.com/wp-content/uploads/2016/01/pantai-sire-lombok.jpg"},
            {"Rumah Adat Suku Sasak Sade", "Lombok Tengah", "Gratis", "Dusun Sade atau Sade Village ini adalah merupakan salah satu Desa Tradisional Sasak (suku asli Pulau Lombok) atau sebuah perkampungan suku Sasak asli yang masih mencoba mempertahankan dan menjaga keaslian sisa – sisa kebudayaan Sasak lama sejak zaman pemerintahan Kerajaan Pejanggik di Praya, Kabupaten Lombok Tengah sampai sekarang.\n" +
                    "Masyarakat yang tinggal di Dusun Sade Lombok ini adalah suku Sasak dengan sistim sosial dan kehidupan keseharian mereka yang masih sangat kental dan memegang teguh adat tradisi Sasak tempo dulu.\n" +
                    "Rumah adat suku Sasak yang juga disebut Bale Tani ini terbuat dari kayu dengan dinding-dinding yang terbuat dari anyaman bambu dan beratapkan daun rumbia atau daun alang-alang kering. Lantai dari Bale Tani ini adalah campuran tanah, getah pohon dan abu jerami yang kemudian diolesi dengan kotoran kerbau. Bale Tani terbagi menjadi dua bagian yaitu Bale Dalam dan Bale Luar. Ruangan Bale Dalam biasanya diperuntukkan untuk anggota keluarga wanita, yang sekaligus merangkap sebagai dapur. Sedangkan ruangan Bale Luar diperuntukkan untuk anggota keluarga lainnya, dan juga berfungsi sebagai ruang tamu.", "https://mytrip123.com/wp-content/uploads/2016/01/Rumah-Adat-Suku-Sasak-Sade-lombok.jpg"},
    };

    public static ArrayList<Wisata> getListData() {
        Wisata wisata = null;
        ArrayList<Wisata> list = new ArrayList<>();
        for (String[] aData : data) {
            wisata = new Wisata();
            wisata.setNama(aData[0]);
            wisata.setLokasi(aData[1]);
            wisata.setTiket(aData[2]);
            wisata.setKeterangan(aData[3]);
            wisata.setFoto(aData[4]);

            list.add(wisata);
        }

        return list;
    }
}
